### ISSUE TITLE
Unknown server location

### ISSUE THREAD

**Issue by Voluted98** [notatallshaw/fall_guys_ping_estimate#44]
Unknown server location while playing in Europe servers. 
[unknown_ip_addresses.csv](https://github.com/notatallshaw/fall_guys_ping_estimate/files/7203504/unknown_ip_addresses.csv)

**Comment by notatallshaw** [comment]
Cool, thanks for the update, appears to be located in Strasbourg and provided by Host Europe GmbH.

How often are you getting unknown servers in Europe? Seems like there's only 1 in your log, I don't play on Europe often so I don't know how good/bad of a job I've done at covering IPs in Europe.

**Comment by Voluted98** [comment]
I only recently started using it and that was the first time I got any unknown server. I think my total usage time might be something like 4h at max.

**Comment by notatallshaw** [comment]
> 
> 
> I only recently started using the program and that was the first time I got any unknown server. I think my total usage time might be something like 4h at max.

Once in 3-4 hours is great, and honestly I might never be able to do better than because of the way Mediatonic provisions it's cloud servers, I was worried it might be something like 50% of all lobbies.

**Comment by notatallshaw** [comment]
Okay, so making a new release for every single new IP Network is kind of annoying.

So what I'm going to is finally implement https://github.com/notatallshaw/fall_guys_ping_estimate/issues/38 , this will mean in the next release it can dynamically update the IP Network list without you having to install a new executable. 

Probably get chance to do it this weekend.

**Comment by mrazishere** [comment]
Firstly, i think scraping the manual location sheet is definitely the way to go, takes a lot of work you maintaining the lists as who knows how often the server list gonna change.

May i suggest using geolocation API like https://ip-api.com/ to feed the reported IP address location and display it on the overlay? it doesn't have to be specific, at least region will be truly helpful to analysis the quality with the ping.

Just a simple single liner to get the region info: `http://ip-api.com/line/$ip-address?fields=regionName`

**Comment by notatallshaw** [comment]
> May i suggest using geolocation API like https://ip-api.com/ to feed the reported IP address location and display it on the overlay? it doesn't have to be specific, at least region will be truly helpful to analysis the quality with the ping.
> 
> Just a simple single liner to get the region info: `http://ip-api.com/line/$ip-address?fields=regionName`

Every API I had at least one of the following problems:

* Accuracy for location was not great
* Required signing up and using some dev token without breaking ToS
* Limited free access to at most 25 queries per day

My solution to this has to been manually check IP addresses against multiple services to check accuracy and then to store the providers CIDR for that IP address so it catches a wide range of IP addresses.

I suspect this API has at least one of the above mentioned problems, but I will experiment with it a little: https://members.ip-api.com/#pricing
